baseURL = 'https://keysense-ai-site.pages.dev/'
languageCode = 'en-us'
title = 'KeySense AI'
theme = 'ananke'  # Ali ime tvoje teme, če uporabljaš drugo

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true